### ISSUE TITLE
Master branch fails to work with opinel=3.0.11

### ISSUE THREAD

**Issue by shivankar-madaan** [nccgroup/Scout2#168]
Got this 
```
Error: Scout2 depends on the opinel package. Install all the requirements with the following command:
  $ pip install -r requirements.txt
cannot import name get_aws_account_id
```
but by running on opinel=3.0.13 it works perfectly fine

**Comment by l01cd3v** [comment]
Thanks, I updated the min version required for opinel.

**Comment by shivankar-madaan** [comment]
Cool
